# Cloud Build configuration for automatic deployments
# Triggers on push to main branch

steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/portfolio", "."]

  # Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/portfolio"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "portfolio"
      - "--image=gcr.io/$PROJECT_ID/portfolio"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--min-instances=0"
      - "--max-instances=2"
      - "--memory=256Mi"
      - "--cpu=1"

images:
  - "gcr.io/$PROJECT_ID/portfolio"

options:
  logging: CLOUD_LOGGING_ONLY
